// Code generated by goctl. DO NOT EDIT.
package handler

import (
	{{.imports}}
)

{{- if.jwtEnabled}}
type jwtCustomClaims struct {
	Name  string `json:"name"`
	Admin bool   `json:"admin"`
	jwt.RegisteredClaims
}
{{- end}}

func RegisterHandlers(server *echo.Echo, svcCtx *svc.ServiceContext) {
	{{.routesAdditions}}

	{{- if not .isService }}

	////////////////////////////////////////////////////////////
	// 404 / Catchall handler
	////////////////////////////////////////////////////////////
	server.Any("/*", notfound.NotFoundHandler(svcCtx))
	{{- end}}
}