// Code generated by soul. DO NOT EDIT.
package auth

import (
	"net/http"

	logicHandler "backend/internal/logic/auth/googlelogin"
	"backend/internal/svc"

	"github.com/labstack/echo/v4"
)

func GetGoogleLoginHandler(svcCtx *svc.ServiceContext, path string) echo.HandlerFunc {
	return func(c echo.Context) error {
		l := logicHandler.NewGoogleLoginLogic(c.Request().Context(), svcCtx)
		resp, err := l.GetGoogleLogin(c)
		if err != nil {
			c.Logger().Error(err)
			return c.JSON(http.StatusInternalServerError, map[string]interface{}{
				"error": "Internal Server Error",
				"msg":   err.Error(),
			})
		}
		return c.JSON(http.StatusOK, resp)
	}
}
