package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// Role represents a row from 'public.roles'.
type Role struct {
	ID          int64        `json:"id" db:"id" form:"id"`                            // id
	PublicID    NullPublicID `json:"public_id" db:"public_id" form:"public_id"`       // public_id
	Name        string       `json:"name" db:"name" form:"name"`                      // name
	Description string       `json:"description" db:"description" form:"description"` // description
	CreatedAt   time.Time    `json:"created_at" db:"created_at" form:"created_at"`    // created_at
	UpdatedAt   time.Time    `json:"updated_at" db:"updated_at" form:"updated_at"`    // updated_at
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Role] exists in the database.
func (r *Role) Exists() bool {
	return r._exists
}

// Deleted returns true when the [Role] has been marked for deletion
// from the database.
func (r *Role) Deleted() bool {
	return r._deleted
}

// Insert inserts the [Role] to the database.
func (r *Role) Insert(ctx context.Context, db DB) error {
	switch {
	case r._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case r._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.roles (` +
		`public_id, name, description, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5` +
		`) RETURNING id`
	// run
	logf(sqlstr, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt)
	if err := db.QueryRowContext(ctx, sqlstr, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt).Scan(&r.ID); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Update updates a [Role] in the database.
func (r *Role) Update(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case r._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.roles SET ` +
		`public_id = $1, name = $2, description = $3, created_at = $4, updated_at = $5 ` +
		`WHERE id = $6`
	// run
	logf(sqlstr, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt, r.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Role] to the database.
func (r *Role) Save(ctx context.Context, db DB) error {
	if r.Exists() {
		return r.Update(ctx, db)
	}
	return r.Insert(ctx, db)
}

// Upsert performs an upsert for [Role].
func (r *Role) Upsert(ctx context.Context, db DB) error {
	switch {
	case r._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.roles (` +
		`id, public_id, name, description, created_at, updated_at` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`public_id = EXCLUDED.public_id, name = EXCLUDED.name, description = EXCLUDED.description, created_at = EXCLUDED.created_at, updated_at = EXCLUDED.updated_at `
	// run
	logf(sqlstr, r.ID, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID, r.PublicID, r.Name, r.Description, r.CreatedAt, r.UpdatedAt); err != nil {
		return logerror(err)
	}
	// set exists
	r._exists = true
	return nil
}

// Delete deletes the [Role] from the database.
func (r *Role) Delete(ctx context.Context, db DB) error {
	switch {
	case !r._exists: // doesn't exist
		return nil
	case r._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.roles ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, r.ID)
	if _, err := db.ExecContext(ctx, sqlstr, r.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	r._deleted = true
	return nil
}

// RoleByID retrieves a row from 'public.roles' as a [Role].
//
// Generated from index 'roles_pkey'.
func RoleByID(ctx context.Context, db DB, id int64) (*Role, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, public_id, name, description, created_at, updated_at ` +
		`FROM public.roles ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	r := Role{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&r.ID, &r.PublicID, &r.Name, &r.Description, &r.CreatedAt, &r.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}

// RoleByPublicID retrieves a row from 'public.roles' as a [Role].
//
// Generated from index 'roles_public_id_key'.
func RoleByPublicID(ctx context.Context, db DB, publicID NullPublicID) (*Role, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, public_id, name, description, created_at, updated_at ` +
		`FROM public.roles ` +
		`WHERE public_id = $1`
	// run
	logf(sqlstr, publicID)
	r := Role{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, publicID).Scan(&r.ID, &r.PublicID, &r.Name, &r.Description, &r.CreatedAt, &r.UpdatedAt); err != nil {
		return nil, logerror(err)
	}
	return &r, nil
}
