package types

const (
	SrcDir          = "src/"
	SrcComponentDir = SrcDir + "components"
	DbDir           = "db"
	MigrationDir    = "db/migrations"
	Internal        = "internal/"
	ChatGptDir      = Internal + "chatgpt"
	ConfigDir       = Internal + "config"
	JobsDir         = Internal + "jobs"
	ContextDir      = Internal + "svc"
	DatabaseDir     = Internal + "database"
	EventsDir       = Internal + "events"
	EmailClientDir  = Internal + "emailclient"
	HandlerDir      = Internal + "handler"
	LayoutsDir      = Internal + "ui/layouts"
	LogicDir        = Internal + "logic"
	MiddlewareDir   = Internal + "middleware"
	ModelsDir       = Internal + "models"
	SecurityDir     = Internal + "security"
	SessionDir      = Internal + "session"
	TokensDir       = Internal + "tokens"
	TypesDir        = Internal + "types" // same as TypesPacket
	UtilsDir        = Internal + "utils"
	ViewDir         = Internal + "views"
	WorkflowDir     = Internal + "workflow"
	ModuleInitDir   = Internal + "moduleinit"
	ModuleDir       = Internal + "modules"
	GroupProperty   = "group"
	PrefixProperty  = "prefix"
	JwtTransKey     = "jwtTransition"
	TypesPacket     = "types"
)
