{
	"name": "{{.serviceName}}",
	"private": true,
	"version": "0.0.1",
	"type": "module",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"build:watch": "vite build --watch",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"format": "prettier --write .",
		"lint": "prettier --check .",
		"css:go": "npx @tailwindcss/cli -i ./assets/css/input.css -o ./assets/css/main.css",
		"css:go:watch": "npx @tailwindcss/cli -i ./assets/css/input.css -o ./assets/css/main.css --watch"
	},
	"devDependencies": {
		"@milkdown/crepe": "^7.6.1",
		"@sveltejs/adapter-auto": "^4.0.0",
		"@sveltejs/adapter-static": "^3.0.8",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^4.0.0",
		"@tailwindcss/forms": "^0.5.10",
		"@tailwindcss/postcss": "^4.0.3",
		"@tailwindcss/typography": "^0.5.16",
		"@tailwindcss/vite": "^4.0.3",
		"@thisux/sveltednd": "^0.0.20",
		"@types/diff": "^7.0.0",
		"autoprefixer": "^10.4.20",
		"daisyui": "5.0.0",
		"htmx.org": "^2.0.4",
		"prettier": "^3.4.2",
		"prettier-plugin-svelte": "^3.3.3",
		"sass-embedded": "^1.83.4",
		"svelte": "^5.0.0",
		"svelte-check": "^4.0.0",
		"typescript": "^5.0.0",
		"uuid": "^11.0.5",
		"vite": "^5.4.11"
	},
	"dependencies": {
		"@tailwindcss/cli": "^4.0.6",
		"@tailwindcss/vite": "^4.0.3",
		"@types/sortablejs": "^1.15.8",
		"chart.js": "^4.4.7",
		"chartjs-adapter-date-fns": "^3.0.0",
		"date-fns": "^4.1.0",
		"date-fns-tz": "^3.2.0",
		"lucide-svelte": "^0.473.0",
		"sortablejs": "^1.15.6",
		"tailwindcss": "^4.0.3"
	}
}