name: Release

on:
  push:
    tags:
      - "v*" # Triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22.2] # Specify the Go version to use
        os: [ubuntu-latest, macos-latest, windows-latest] # OS matrix

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('tools/soul/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Install dependencies
        run: go mod download
        working-directory: ./tools/soul

      - name: Build binary
        run: |
          mkdir -p tools/soul/dist
          GOOS=$(echo ${{ matrix.os }} | cut -d- -f1)
          GOARCH=amd64
          go build -o tools/soul/dist/soul-${GOOS}-${GOARCH} .
        working-directory: ./tools/soul

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: soul-${{ matrix.os }}
          path: tools/soul/dist/soul-${{ matrix.os }}-amd64

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: tools/soul/dist/*
          asset_name: soul-*
          asset_content_type: application/octet-stream
